// javascript/77/hw/src/Address.jsx
import React, { Component } from 'react';
import './Address.css';

export default class Address extends Component {
    render() {
        const { street, city, state, zip } = this.props.address;

        return (
            <div>
                <h4>{street}</h4>
                <h4 className="city">{city}</h4>
                <h4>{state}</h4>
                <h4 style={{ color: 'red', textDecoration: 'underline' }}>{zip}</h4>
            </div>
        );
    }
}

// javascript/83/HW/src/app/address/address.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Address } from '../shared/address';

@Component({
  selector: 'app-address',
  templateUrl: './address.component.html',
  styleUrls: ['./address.component.css']
})
export class AddressComponent {
  @Input()
  address: Address;
}

<ul>
  <li>{{address.street}}</li>
  <li>{{address.city}}</li>
  <li>{{address.state}}</li>
  <li>{{address.zip}}</li>
</ul>
